name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v2

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Instalar dependencias
      run: composer install

    - name: Ejecutar migraciones
      run: php artisan migrate --force

    - name: Limpiar caché
      run: php artisan config:cache
